### ISSUE TITLE
Implement physical memory model

### ISSUE THREAD

**Issue by mmamayka** [BESM-Consortium/BESM-666#24]
Implement physical memory model that supports:
- address space of size at least 256GB
- loading ELF files & continuous data areas into the memory during the construction
- stable minimal interface for physical memory interaction
Unit test the developed functional

**Comment by 0pdd** [comment]
@mmamayka the puzzle [#31](https://github.com/BESM-Consortium/BESM-666/issues/31) is still not solved.
