### ISSUE TITLE
Load and run ELF

### ISSUE THREAD

**Issue by c71n93** [BESM-Consortium/BESM-666#9]
Use [ELFIO](https://github.com/serge1/ELFIO)

- Load PIC ELF to memory of the process
- Validate ELF target arch, lack of `.rela.plt` & `.rela.dyn` sections
- Run the ELF from entry point
- UNIT TEST it!

**Comment by mmamayka** [comment]
I have added `besm::mem::PhysMemBuilder::loadElf(std::filesystem::path)` method w/o implementation, that should load ELF file into the simulated physical memory to addresses specified in the file. I think, it should be a entry point of your implementation

**Comment by 0pdd** [comment]
@c71n93 the puzzle [#50](https://github.com/BESM-Consortium/BESM-666/issues/50) is still not solved.
